package url.example.urlShortner.Services;


import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.stereotype.Service;
import url.example.urlShortner.DTOs.ClickEventMessage;
import url.example.urlShortner.DTOs.ClickEventDTO;
import url.example.urlShortner.DTOs.UrlMappingDTO;
import url.example.urlShortner.Model.ClickEvent;
import url.example.urlShortner.Model.UrlMapping;
import url.example.urlShortner.Model.User;
import url.example.urlShortner.Repository.ClickEventRepository;
import url.example.urlShortner.Repository.UrlMappingRepository;
import url.example.urlShortner.Util.Base62Encoder;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Service
public class UrlMappingService {
    private final UrlMappingRepository urlMappingRepository;
    private final ClickEventRepository clickEventRepository;
    private final ClickEventProcessor clickEventProcessor;

    public UrlMappingService(UrlMappingRepository urlMappingRepository, 
                             ClickEventRepository clickEventRepository, 
                             ClickEventProcessor clickEventProcessor) {
        this.urlMappingRepository = urlMappingRepository;
        this.clickEventRepository = clickEventRepository;
        this.clickEventProcessor = clickEventProcessor;
    }

    /**
     * Creates a shortened URL using Base62 encoding of the database-generated ID.
     *
     * <p><b>Flow:</b>
     * <ol>
     *   <li>Save entity to PostgreSQL → auto-generates a unique Long ID</li>
     *   <li>Base62-encode that ID → produces a compact, unique short code</li>
     *   <li>Update the entity with the computed short code</li>
     * </ol>
     *
     * <p><b>Why two saves?</b> The ID is generated by PostgreSQL's IDENTITY strategy
     * on the first INSERT. We need this ID to compute the Base62 code.
     * The second UPDATE is by primary key — sub-millisecond.
     *
     * <p><b>Collision safety:</b> Since each unique Long ID maps to exactly one
     * unique Base62 string (bijective function), collisions are mathematically impossible.
     *
     * @param originalUrl the URL to shorten
     * @param user the authenticated user creating the URL
     * @return DTO containing the shortened URL details
     */
    public UrlMappingDTO createShortUrl(String originalUrl, User user) {
        // Step 1: Save entity to get the auto-generated database ID
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setOriginalUrl(originalUrl);
        urlMapping.setUser(user);
        urlMapping.setCreatedDate(LocalDateTime.now());
        UrlMapping savedUrlMapping = urlMappingRepository.save(urlMapping);

        // Step 2: Base62-encode the database ID to generate the short code
        String shortUrl = Base62Encoder.encode(savedUrlMapping.getId());

        // Step 3: Update the entity with the generated short code
        savedUrlMapping.setShortUrl(shortUrl);
        UrlMapping updatedUrlMapping = urlMappingRepository.save(savedUrlMapping);

        log.info("Created short URL: {} → {} (id={})",
                shortUrl, originalUrl, updatedUrlMapping.getId());

        return convertToDto(updatedUrlMapping);
    }

    private UrlMappingDTO convertToDto(UrlMapping urlMapping){
        UrlMappingDTO urlMappingDTO = new UrlMappingDTO();
        urlMappingDTO.setId(urlMapping.getId());
        urlMappingDTO.setOriginalUrl(urlMapping.getOriginalUrl());
        urlMappingDTO.setShortUrl(urlMapping.getShortUrl());
        urlMappingDTO.setClickCount(urlMapping.getClickCount());
        urlMappingDTO.setCreatedDate(urlMapping.getCreatedDate());
        urlMappingDTO.setUsername(urlMapping.getUser().getUsername());
        return urlMappingDTO;
    }

    public List<UrlMappingDTO> getUrlsByUser(User user) {
        return urlMappingRepository.findByUser(user).stream()
                .map(this::convertToDto)
                .toList();
    }

    public List<ClickEventDTO> getClickEventsByDate(String shortUrl, LocalDateTime start, LocalDateTime end) {
        UrlMapping urlMapping = urlMappingRepository.findByShortUrl(shortUrl);
        if (urlMapping != null) {
            return clickEventRepository.findByUrlMappingAndClickDateBetween(urlMapping, start, end).stream()
                    .collect(Collectors.groupingBy(click -> click.getClickDate().toLocalDate(), Collectors.counting()))
                    .entrySet().stream()
                    .map(entry -> {
                        ClickEventDTO clickEventDTO = new ClickEventDTO();
                        clickEventDTO.setClickDate(entry.getKey());
                        clickEventDTO.setCount(entry.getValue());
                        return clickEventDTO;
                    })
                    .collect(Collectors.toList());
        }
        return null;
    }

    public Map<LocalDate, Long> getTotalClicksByUserAndDate(User user, LocalDate start, LocalDate end) {
        List<UrlMapping> urlMappings = urlMappingRepository.findByUser(user);
        List<ClickEvent> clickEvents = clickEventRepository.findByUrlMappingInAndClickDateBetween(urlMappings, start.atStartOfDay(), end.plusDays(1).atStartOfDay());
        return clickEvents.stream()
                .collect(Collectors.groupingBy(click -> click.getClickDate().toLocalDate(), Collectors.counting()));
    }

    public UrlMapping getOriginalUrl(String shortUrl, jakarta.servlet.http.HttpServletRequest request) {
        UrlMapping urlMapping = urlMappingRepository.findByShortUrl(shortUrl);
        if (urlMapping != null) {
            try {
                ClickEventMessage clickMessage = new ClickEventMessage();
                clickMessage.setUrlMappingId(urlMapping.getId());

                if (request != null) {
                    clickMessage.setUtmSource(request.getParameter("utm_source"));
                    clickMessage.setUtmMedium(request.getParameter("utm_medium"));
                    clickMessage.setUtmCampaign(request.getParameter("utm_campaign"));
                    clickMessage.setReferer(request.getHeader("referer"));
                    clickMessage.setUserAgent(request.getHeader("User-Agent"));

                    String ip = request.getHeader("X-Forwarded-For");
                    if (ip == null || ip.isEmpty()) {
                        ip = request.getRemoteAddr();
                    }
                    clickMessage.setIp(ip);
                }

                clickEventProcessor.processClickEventAsync(clickMessage);

            } catch (Exception e) {
                log.error("Error initiating async click event processing", e);
            }
        }
        return urlMapping;
    }
}
